---
- hosts: all
  become: true
  tasks:
  - name: Enabling to login with password 
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication '
      line: 'PasswordAuthentication yes'

  - name: Restarting SSHD Service
    service:
      name: sshd
      state: restarted
