---
- hosts: cont
  become: true
    tasks:
    - name: Install Apache Webserver
      apt: pkg=httpd state=latest
    - name: Enable Apache on system reboot
      service: name=httpd enabled=yes
      notify: restart apache
    handlers:
    - name: restart apache
      service: name=httpd state=restarted
