---
- hosts: all
  become: true
  tasks:
  - name: setting primary and secondary name server
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: "{{ item.line }}"
      state: present
    with_items:
    - { line: 'DNS1=10.0.0.0' }
    - { line: 'DNS2=10.0.0.1' }

  - name: Restarting Network 
    service:
      name: network
      state: restarted
